spring:
  application:
    name: alert-service
  profiles:
    active: dev # 또는 prod, 실행 환경에 따라 자동으로 바뀜

  session:
    redis:
      namespace: "spring:session"
      flush-mode: on_save
      save-mode: on_set_attribute

  data:
    redis:
      repositories:
        enabled: false

server:
  port: 8080

logging:
  level:
    root: INFO
    com.yourcompany.alertservice: INFO