spring:
  application:
    name: drivecast-service
  profiles:
    active: prod

  session:
    redis:
      namespace: "spring:session"
      flush-mode: on_save
      save-mode: on_set_attribute

  data:
    redis:
      repositories:
        enabled: false

  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  expiration: 3600000 # 1시간

server:
  port: 8080

logging:
  level:
    root: INFO
    com.smooth.drivecast_service: DEBUG
    # Redis 연결 로그 최소화
    org.springframework.data.redis.core.RedisConnectionUtils: WARN
    org.springframework.data.redis.connection: WARN
    # 스케줄러 관련 로그 제어
    org.springframework.scheduling: INFO
    # HTTP 요청 로그 (개발용)
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    # Feign 클라이언트 로그 (개발용)
    feign: DEBUG
