spring:
  application:
    name: drivecast-service
  profiles:
    active: dev  # 기본 프로파일 설정

  session:
    redis:
      namespace: "spring:session"
      flush-mode: on_save
      save-mode: on_set_attribute

  data:
    redis:
      repositories:
        enabled: false

  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  expiration: 3600000 # 1시간

server:
  port: 8080

logging:
  level:
    root: INFO
    com.smooth.alert_service: INFO
