spring:
  data:
    redis:
      host: valkey-prod.xxxxxx.cache.amazonaws.com
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 3000ms

  datasource:
    url: jdbc:mysql://prod-db-host:3306/alert_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 3000
            loggerLevel: none

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: false
        show_sql: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1시간

logging:
  level:
    root: INFO
    com.yourcompany.alertservice: INFO
    org.springframework.web: WARN